const SECTIONS = [
    {
        id: 1,
        title: 'Механика',
        formulas: [
            // Кинематика
            { id: 1,  kim: 1, раздел: 'Кинематика', prompt: 'Скорость при равномерном движении.',                                                    image: 'mechanics/kinematics/1.png' },
            { id: 2,  kim: 1, раздел: 'Кинематика', prompt: 'Путь при равномерном движении.',                                                        image: 'mechanics/kinematics/2.png' },
            { id: 3,  kim: 1, раздел: 'Кинематика', prompt: 'Координата при равномерном движении. Закон движения.',                                   image: 'mechanics/kinematics/3.png' },
            { id: 4,  kim: 1, раздел: 'Кинематика', prompt: 'Скорость при равноускоренном движении.',                                                 image: 'mechanics/kinematics/4.png' },
            { id: 5,  kim: 1, раздел: 'Кинематика', prompt: 'Ускорение при равноускоренном движении.',                                                image: 'mechanics/kinematics/5.png' },
            { id: 6,  kim: 1, раздел: 'Кинематика', prompt: 'Средняя скорость при равноускоренном движении.',                                         image: 'mechanics/kinematics/6.png' },
            { id: 7,  kim: 1, раздел: 'Кинематика', prompt: 'Путь при равноускоренном движении.',                                                     image: 'mechanics/kinematics/7.png' },
            { id: 8,  kim: 1, раздел: 'Кинематика', prompt: 'Перемещение при равноускоренном движении.',                                              image: 'mechanics/kinematics/8.png' },
            { id: 9,  kim: 1, раздел: 'Кинематика', prompt: 'Координата при равноускоренном движении. Закон движения.',                               image: 'mechanics/kinematics/9.png' },
            { id: 10, kim: 1, раздел: 'Кинематика', prompt: 'Путь при равноускоренном движении. Через скорость и ускорение.',                         image: 'mechanics/kinematics/10.png' },
            { id: 11, kim: 1, раздел: 'Кинематика', prompt: 'Период движения по окружности.',                                                         image: 'mechanics/kinematics/11.png' },
            { id: 12, kim: 1, раздел: 'Кинематика', prompt: 'Частота.',                                                                               image: 'mechanics/kinematics/12.png' },
            { id: 13, kim: 1, раздел: 'Кинематика', prompt: 'Ускорение при движении по окружности.',                                                  image: 'mechanics/kinematics/13.png' },
            { id: 14, kim: 1, раздел: 'Кинематика', prompt: 'Угловая скорость при движении по окружности. Через период.',                             image: 'mechanics/kinematics/14.png' },
            { id: 15, kim: 1, раздел: 'Кинематика', prompt: 'Линейная скорость при движении по окружности. Через угловую скорость.',                  image: 'mechanics/kinematics/15.png' },
            // Динамика
            { id: 16, kim: 2, раздел: 'Динамика', prompt: 'Второй закон Ньютона.',                                                                    image: 'mechanics/dynamics/16.png' },
            { id: 17, kim: 2, раздел: 'Динамика', prompt: 'Сила упругости. Закон Гука.',                                                              image: 'mechanics/dynamics/17.png' },
            { id: 18, kim: 2, раздел: 'Динамика', prompt: 'Сила притяжения. Закон всемирного тяготения.',                                             image: 'mechanics/dynamics/18.png' },
            { id: 19, kim: 2, раздел: 'Динамика', prompt: 'Скорость спутника на орбите.',                                                             image: 'mechanics/dynamics/19.png' },
            { id: 20, kim: 2, раздел: 'Динамика', prompt: 'Период обращения спутника.',                                                               image: 'mechanics/dynamics/20.png' },
            { id: 21, kim: 2, раздел: 'Динамика', prompt: 'Сила реакции опоры. Нормаль.',                                                             image: 'mechanics/dynamics/21.png' },
            { id: 22, kim: 2, раздел: 'Динамика', prompt: 'Сила трения скольжения.',                                                                  image: 'mechanics/dynamics/22.png' },
            { id: 23, kim: 2, раздел: 'Динамика', prompt: 'Жёсткость системы двух параллельно соединённых пружин.',                                   image: 'mechanics/dynamics/23.png' },
            { id: 24, kim: 2, раздел: 'Динамика', prompt: 'Жёсткость системы двух последовательно соединённых пружин.',                               image: 'mechanics/dynamics/24.png' },
            // Законы сохранения
            { id: 25, kim: 3, раздел: 'Законы сохранения', prompt: 'Импульс тела.',                                                                   image: 'mechanics/conservationOfEnergy/25.png' },
            { id: 26, kim: 3, раздел: 'Законы сохранения', prompt: 'Закон сохранения импульса.',                                                      image: 'mechanics/conservationOfEnergy/26.png' },
            { id: 27, kim: 3, раздел: 'Законы сохранения', prompt: 'Импульс силы. Изменение импульса при влиянии силы.',                              image: 'mechanics/conservationOfEnergy/27.png' },
            { id: 28, kim: 3, раздел: 'Законы сохранения', prompt: 'Механическая работа. Общая формула.',                                             image: 'mechanics/conservationOfEnergy/28.png' },
            { id: 29, kim: 3, раздел: 'Законы сохранения', prompt: 'Мощность.',                                                                       image: 'mechanics/conservationOfEnergy/29.png' },
            { id: 30, kim: 3, раздел: 'Законы сохранения', prompt: 'Мощность при равномерном движении без ускорения.',                                image: 'mechanics/conservationOfEnergy/30.png' },
            { id: 31, kim: 3, раздел: 'Законы сохранения', prompt: 'Кинетическая энергия.',                                                           image: 'mechanics/conservationOfEnergy/31.png' },
            { id: 32, kim: 3, раздел: 'Законы сохранения', prompt: 'Изменение кинетической энергии за счёт работы.',                                  image: 'mechanics/conservationOfEnergy/32.png' },
            { id: 33, kim: 3, раздел: 'Законы сохранения', prompt: 'Потенциальная энергия тела на высоте.',                                           image: 'mechanics/conservationOfEnergy/33.png' },
            { id: 34, kim: 3, раздел: 'Законы сохранения', prompt: 'Потенциальная энергия деформированной пружины.',                                  image: 'mechanics/conservationOfEnergy/34.png' },
            { id: 35, kim: 3, раздел: 'Законы сохранения', prompt: 'Полная механическая энергия.',                                                    image: 'mechanics/conservationOfEnergy/35.png' },
            { id: 36, kim: 3, раздел: 'Законы сохранения', prompt: 'Закон сохранения полной механической энергии.',                                   image: 'mechanics/conservationOfEnergy/36.png' },
            // Статика
            { id: 37, kim: 4, раздел: 'Статика', prompt: 'Момент силы.',                                                                              image: 'mechanics/statics/37.png' },
            { id: 38, kim: 4, раздел: 'Статика', prompt: 'Условие равновесия рычага.',                                                                image: 'mechanics/statics/38.png' },
            { id: 39, kim: 4, раздел: 'Статика', prompt: 'Давление. Общая формула.',                                                                  image: 'mechanics/statics/39.png' },
            { id: 40, kim: 4, раздел: 'Статика', prompt: 'Давление водяного столба.',                                                                 image: 'mechanics/statics/40.png' },
            { id: 41, kim: 4, раздел: 'Статика', prompt: 'Сила Архимеда.',                                                                            image: 'mechanics/statics/41.png' },
            { id: 42, kim: 4, раздел: 'Статика', prompt: 'Условие плавания тела.',                                                                    image: 'mechanics/statics/42.png' },
        ]
    },
    {
        id: 2,
        title: 'Колебания и волны',
        formulas: [
            { id: 43, kim: 4, раздел: 'Колебания и волны', prompt: 'Частота через период.',                       image: 'oscillationsAndWaves/43.png' },
            { id: 44, kim: 4, раздел: 'Колебания и волны', prompt: 'Циклическая частота.',                        image: 'oscillationsAndWaves/44.png' },
            { id: 45, kim: 4, раздел: 'Колебания и волны', prompt: 'Уравнение гармонических колебаний.',          image: 'oscillationsAndWaves/45.png' },
            { id: 46, kim: 4, раздел: 'Колебания и волны', prompt: 'Период колебаний пружинного маятника.',       image: 'oscillationsAndWaves/46.png' },
            { id: 47, kim: 4, раздел: 'Колебания и волны', prompt: 'Период колебаний математического маятника.',  image: 'oscillationsAndWaves/47.png' },
            { id: 48, kim: 4, раздел: 'Колебания и волны', prompt: 'Длина волны.',                                image: 'oscillationsAndWaves/48.png' },
            { id: 49, kim: 4, раздел: 'Колебания и волны', prompt: 'Скорость распространения волны.',             image: 'oscillationsAndWaves/49.png' },
        ]
    },
    {
        id: 3,
        title: 'Молекулярная физика',
        formulas: [
            { id: 50, kim: 7, раздел: 'Молекулярная физика', prompt: 'Правила перевода температуры.',                                        image: 'molecularPhysics/50.png' },
            { id: 51, kim: 7, раздел: 'Молекулярная физика', prompt: 'Средняя кинетическая энергия одноатомного газа.',                      image: 'molecularPhysics/51.png' },
            { id: 52, kim: 7, раздел: 'Молекулярная физика', prompt: 'Уравнение состояния идеального газа.',                                 image: 'molecularPhysics/52.png' },
            { id: 53, kim: 7, раздел: 'Молекулярная физика', prompt: 'Уравнение Клайперона (масса постоянна).',                              image: 'molecularPhysics/53.png' },
            { id: 54, kim: 7, раздел: 'Молекулярная физика', prompt: 'Уравнение Менделеева — Клайперона (с учётом массы).',                  image: 'molecularPhysics/54.png' },
            { id: 55, kim: 7, раздел: 'Молекулярная физика', prompt: 'Основное уравнение МКТ.',                                              image: 'molecularPhysics/55.png' },
            { id: 56, kim: 7, раздел: 'Молекулярная физика', prompt: 'Количество вещества (моль).',                                          image: 'molecularPhysics/56.png' },
            { id: 57, kim: 7, раздел: 'Молекулярная физика', prompt: 'Изотермический процесс. Закон Бойля-Мариотта.',                        image: 'molecularPhysics/57.png' },
            { id: 58, kim: 7, раздел: 'Молекулярная физика', prompt: 'Изобарный процесс. Закон Гей-Люссака.',                                image: 'molecularPhysics/58.png' },
            { id: 59, kim: 7, раздел: 'Молекулярная физика', prompt: 'Изохорный процесс. Закон Шарля.',                                      image: 'molecularPhysics/59.png' },
            { id: 60, kim: 8, раздел: 'Термодинамика',       prompt: 'Внутренняя энергия одноатомного газа.',                                image: 'molecularPhysics/60.png' },
            { id: 61, kim: 8, раздел: 'Термодинамика',       prompt: 'Работа газа на PV-диаграмме.',                                         image: 'molecularPhysics/61.png' },
            { id: 62, kim: 8, раздел: 'Термодинамика',       prompt: 'Работа газа / работа над газом.',                                      image: 'molecularPhysics/62.png' },
            { id: 63, kim: 8, раздел: 'Термодинамика',       prompt: 'Первый закон термодинамики. Общий вид.',                               image: 'molecularPhysics/63.png' },
            { id: 64, kim: 8, раздел: 'Термодинамика',       prompt: 'Первый закон термодинамики для изобарного процесса.',                  image: 'molecularPhysics/64.png' },
            { id: 65, kim: 8, раздел: 'Термодинамика',       prompt: 'Первый закон термодинамики для изохорного процесса.',                  image: 'molecularPhysics/66.png' },
            { id: 66, kim: 8, раздел: 'Термодинамика',       prompt: 'Первый закон термодинамики для изотермического процесса.',             image: 'molecularPhysics/65.png' },
            { id: 67, kim: 8, раздел: 'Термодинамика',       prompt: 'Первый закон термодинамики для адиабатного процесса.',                 image: 'molecularPhysics/67.png' },
            { id: 68, kim: 8, раздел: 'Термодинамика',       prompt: 'Полезная работа теплового двигателя.',                                 image: 'molecularPhysics/68.png' },
            { id: 69, kim: 8, раздел: 'Термодинамика',       prompt: 'КПД теплового двигателя через работу.',                                image: 'molecularPhysics/69.png' },
            { id: 70, kim: 8, раздел: 'Термодинамика',       prompt: 'КПД теплового двигателя.',                                             image: 'molecularPhysics/70.png' },
            { id: 71, kim: 8, раздел: 'Термодинамика',       prompt: 'КПД тепловой машины Карно.',                                           image: 'molecularPhysics/71.png' },
            { id: 72, kim: 8, раздел: 'Термодинамика',       prompt: 'Количество теплоты через удельную теплоёмкость. Нагрев и охлаждение.', image: 'molecularPhysics/72.png' },
            { id: 73, kim: 8, раздел: 'Термодинамика',       prompt: 'Количество теплоты через удельную теплоту. Разные процессы.',          image: 'molecularPhysics/73.png' },
            { id: 74, kim: 8, раздел: 'Термодинамика',       prompt: 'Уравнение теплового баланса.',                                         image: 'molecularPhysics/74.png' },
        ]
    },
];